--Populating genre
INSERT IGNORE INTO genre(intitule) VALUES('DIANA');
INSERT IGNORE INTO genre(intitule) VALUES('OXFORD');
INSERT IGNORE INTO genre(intitule) VALUES('SPECIAL');
INSERT IGNORE INTO genre(intitule) VALUES('SOUPER');
INSERT IGNORE INTO genre(intitule) VALUES('SOUPLEX');
INSERT IGNORE INTO genre(intitule) VALUES('ABS');
INSERT IGNORE INTO genre(intitule) VALUES('NASSIM');
INSERT IGNORE INTO genre(intitule) VALUES('TRANSITION');
